name: example-service
services:
  cds-go-dev:
    hostname: cds-go-dev
    healthcheck:
      test:
        - CMD-SHELL
        - echo cds-go-dev OK
    image: cds-harbor.rtplab.nimblestorage.com/devops/cds-go-dev:latest
    networks:
      - example-service
    volumes:
      - $HOME/.gitconfig:/home/dev/.gitconfig
      - $HOME/.ssh:/home/dev/.ssh
      - example-service-repo:/home/dev/ws/example-service
      - go-dir:/home/dev/go
      - go-cache:/home/dev/.cache
    working_dir: /home/dev/ws/example-service

volumes:
  example-service-repo:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":/System/Volumes/Data/${PWD}"
  go-dir: {}
  go-cache: {}

networks:
  example-service:
    name: local
